### ISSUE TITLE
ssh key required when cloning submodules

### ISSUE THREAD

**Issue by yhhshb** [ByteHamster/SicHash#1]
Hello @ByteHamster,

Cloning recursively SicHash as a submodule of another project fails.
SicHash itself is imported correctly, but downloading its submodules (namely: simpleRibbon and util) fails due to permission issues.

> [git@github.com](mailto:git@github.com): Permission denied (publickey). 
> fatal: Could not read from remote repository.
>Please make sure you have the correct access rights and the repository exists.

I think the culprit is that ssh is used instead of https, e.g. : https://github.com/ByteHamster/SicHash/blob/de0d010c952e3c8b6b61f699a0211c570aba22e3/.gitmodules#L3

Would it be possible to switch to https?

**Comment by ByteHamster** [comment]
I switched to https submodules in 9940ae83cc1fd88703929bcbdc21cb3eb6212945

**Comment by yhhshb** [comment]
Thanks!
