### ISSUE TITLE
Missing <tbb/concurrent_queue.h>

### ISSUE THREAD

**Issue by yhhshb** [ByteHamster/SicHash#2]
Hi @ByteHamster ,

While trying to use your library as a submodule of [lphash](https://github.com/jermp/lphash/tree/dev) I am unable to include <tbb/concurrent_queue.h> .
I tried using `sudo apt install libtbb-dev` on a Ubuntu box without success.

Can you please tell me how you installed it?

Thanks in advance.

**Comment by ByteHamster** [comment]
Hi, I also simply installed the `libtbb-dev` package. According to the [Ubuntu website](https://packages.ubuntu.com/jammy/amd64/libtbb-dev/filelist), the package does contain the file `/usr/include/tbb/concurrent_queue.h`.

The following Dockerfile does build for me, and the only relevant packages are `libtbb-dev` and `libxxhash-dev`:
https://github.com/ByteHamster/SicHash/blob/main/Dockerfile

**Comment by ByteHamster** [comment]
Hi @yhhshb, did you manage to solve the issue?
