### ISSUE TITLE
CPU of paper experiments

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [ByteHamster/SicHash#5]
Hey,

In the SicHash paper, you write:

> Experimental Setup. We run our experiments on an Intel Xeon E5-2670 v3 with a base clock speed of 2.3 GHz. The L1, L2, and L3 caches have a size of 768 KiB, 6 MiB, and 60 MiB, respectively.

Some comments:
- [Intel](https://www.intel.com/content/www/us/en/products/sku/81709/intel-xeon-processor-e52670-v3-30m-cache-2-30-ghz/specifications.html) lists this CPU as having 12 cores / 24 threads and 30MiB L3 cache. Did you run on a dual-socket machine?
- The L1 and L2 cache you report are total (over 24 cores, I assume), instead of the usual per-core numbers.

This is quite relevant, since your largest experiments in fig 6 use 2*10^8 keys, which takes around 48MB at 2 bits/key, and hence either fit or do not fit in the cache.

**Comment by ByteHamster** [comment]
Hi!

> Intel lists this CPU as having 12 cores / 24 threads and 30MiB L3 cache. Did you run on a dual-socket machine?
> The L1 and L2 cache you report are total (over 24 cores, I assume), instead of the usual per-core numbers.

Yeah, it's a dual-socket machine. I must admit that's a weird choice for single-threaded experiments. We didn't have a normal consumer machine in our cluster back then.

> since your largest experiments in fig 6 use 2*10^8 keys

If you are interested in that plot, we have a version with more competitors in my thesis in Figure 8.3 here: https://publikationen.bibliothek.kit.edu/1000176432/155628357 That one uses a more standard machine (single-socket Intel i7 11700, 30MB cache). Also, IIRC, it uses slightly different configurations of each competitor compared to the SicHash paper. The exact configurations are listed in Table 8.1 (the ones with asterisk).

![grafik](https://github.com/user-attachments/assets/02d074fd-3e0d-441f-818e-95b696c25004)

**Comment by RagnarGrootKoerkamp** [comment]
Thanks for confirming :)
I wonder how 60MB cache works on dual socket machines. I'd suspect that in single-threaded mode, the 30MB cache of the same CPU is (much?) faster than the 30MB on the other half. Or maybe they can't even use the 30MB of the other half at all. (No idea really; I don't have experience with dual-socket machines.)

So anyway, I'm currently writing up PtrHash [here](https://curiouscoding.nl/posts/ptrhash-paper). Would be happy to hear your feedback in case you read it :)
